### ISSUE TITLE
Create Drush role

### ISSUE THREAD

**Issue by EmlynK** [codeenigma/ansible-provision#34]
While Drupal 7 sites are being supported, it would be good to have a role to install Drush as currently, Drush is only installed during a deployment. With an ASG setup, when the cluster is rebuilt, Drush **won't** be installed which means Drush commands cannot be run against a Drupal 7 site until a deployment is done.

This will also apply to if a new server is added to the pool due to an autoscale event.

**Comment by gregharvey** [comment]
Closing, this is handled by ce-deploy.
